quarkus.log.level=INFO
quarkus.log.category."net.dahanne".level=DEBUG

quarkus.container-image.buildpack.environment-variables=BP_JVM_VERSION=21
#quarkus.buildpack.jvm-builder-image=pifpaf
renew.frequency=24h
renew.trigger.days=8
renew.email.destination=
